### ISSUE TITLE
review screen problems

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTFeeWaiver#40]
Michelle and I are having problems with getting ALIncome things to work in the review screen. Specifically I want to display the word "None" under categories where they did not select anything (try saying none of the above to everything). Can't get that to happen. I also want the user to be able to Add an item in the review screen. I'm not having luck. (Try saying you have a piece of real_estate and a bank_asset then try to add. For real_estate you get Error There appears to be an infinite loop. Variables in stack are x.source. For bank_assets they disappear from the review screen when you add one.) Do you know of any fixes or workarounds to get this to work? Here's my repository and I commented out the user info so I can jump into the incomes, expenses and assets quickly in the interview.
 
Michelle B she/her (Guest)
Just to add to the report: I believe the object we were troubleshooting was an ALExpenseList. Even though we input that the user had no expenses, the ALExpenseList had two items. The items had very few properties. For example, no value. We couldn't find where those items are being added. Even trying to put expenses.revisit under Edit was enough to cause an error that wouldn't show the section on the review screen. We can get the "variables and values". Other objects were also having problems, but we didn't look into those.

**Comment by tobyfey** [comment]
The main problem is that the ALIncome things are not being gathered when "None of the Above" is selected.  A list that isn't gathered is the same as a variable that is undefined in a review screen - it just won't show up.  To fix this, we need to make sure the lists are gathered before the review screen.

**Comment by VTskier** [comment]
Ah, good explanation! I just had a similar thing happen on another interview where I collected user info but had not actually included "users.gather()" in the interview order! When I added it, the info appeared on the review screen.

Feel free to fix that problem. Thanks!

**Comment by VTskier** [comment]
@tobyfey Is this ready to be merged into main? https://github.com/LSVermont/docassemble-VTFeeWaiver/tree/ReviewScreenGatheredFix
