### ISSUE TITLE
branch: WorkingOnJobsTipsBonuses812024    gathering tips,bonuses,commissions and editing pay and tips,bonuses,commissions

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTFeeWaiver#42]
See notes below.

**Comment by VTskier** [comment]
When entering a job, I have made custom screens to ask user if they also have tips commissions or bonuses at that job. 

If I say yes, I have a bonus every year, I can enter the amount. But when I continue I get an error. 
_There appears to be an infinite loop. Variables in stack are x.complete, x.there_are_any._

If I say no and continue, I get the same error.

FYI, for this form I do not need to collect deductions from pay (x.to_subtract). On the next financial forms we will collect that info.

**Comment by VTskier** [comment]
Then, on custom screen id: other itemized job income value, I want to be able to edit my pay or my tips/bonuses/commissions. The wording needs to be different depending on whether I'm editing pay or tips/bonuses/commissions.

**The default AL screen didn't have proper wording to handle this. That is why we were attempting to make the custom screens above to collect the info, and then trigger the proper wording and questions when editing.**

FEEL FREE TO SUGGEST ANOTHER WAY TO DO THIS.

**Comment by tobyfey** [comment]
![image](https://github.com/user-attachments/assets/735ef392-afe1-4199-b208-329eb978085e)
It would be easier to use this type of dropdown than the selected_types method.  Would it work?
