### ISSUE TITLE
id: info for each vehicle -- want to use my custom question 

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTFeeWaiver#48]
instead of the one from from docassemble.ALToolbox:al_income.yml

**Comment by tobyfey** [comment]
An ALVehicle has a default .source of 'vehicle', so the dropdown menu for source won't be set to other, and if other is chosen, then "vehicle" will already be in the .source text box.

**Comment by VTskier** [comment]
OK. I think I know what you mean and it's fine. Thanks!
