### ISSUE TITLE
Suggestions for list there_is_another pages

### ISSUE THREAD

**Issue by tobyfey** [LSVermont/docassemble-VTFeeWaiver#68]
Quinten had the following suggestions based on best practices

Always avoid using yes no buttons, because they are bad for accessibility
![image](https://github.com/user-attachments/assets/e9ec67ea-970d-4150-b6c7-ffe8b1309ebd)

We could change the yesno to radio buttons, or use an add another like this

![image](https://github.com/user-attachments/assets/fc1fdc80-4b7b-43d7-88e7-770c8cf69b88)

He also said to remove periods at the end of headings

**Comment by VTskier** [comment]
The Add another button is good:
[image.png (view on web)](https://github.com/user-attachments/assets/fc1fdc80-4b7b-43d7-88e7-770c8cf69b88)

**Comment by VTskier** [comment]
@tobyfey Can you switch those to the Add another button? I'll work on other things so I can get the interview to my colleagues to test it.

**Comment by tobyfey** [comment]
Yes, working on this now.
